### ISSUE TITLE
Parameter injection of Resources does not clean up

### ISSUE THREAD

**Issue by saadlu** [asarkar/grpc-test#12]
Hi Again,

I am trying out parameter injection of `Resources`.

See https://github.com/saadlu/helloworld-grpc-test/blob/main/src/test/java/net/saad/learning/grpc/hello/HelloWorldServerJ5ParameterInjectionTest.java

I put a breakpoint at Resources::clean (https://github.com/asarkar/grpc-test/blob/master/src/main/kotlin/com/asarkar/grpc/test/Resources.kt#L65), and it does not hit when I run the above test in debug mode.

For instance field of Resources the breakpoint does hit. So test https://github.com/saadlu/helloworld-grpc-test/blob/main/src/test/java/net/saad/learning/grpc/hello/HelloWorldServerJ5Test.java does clean up.

I have also trying putting breakpoints in `io.grpc.internal.ServerImpl#shutdown` and it does not hit when parameter injection is used but does hit when instance field of Resources is used.

I am not sure if I am doing something wrong.

But I did ran your test

https://github.com/asarkar/grpc-test/blob/master/src/test/kotlin/com/asarkar/grpc/test/GrpcCleanupExtensionIntegrationTests.kt#L22

and it fails for me, too.

```java
Wanted but not invoked:
server.shutdown();
-> at com.asarkar.grpc.test.GrpcCleanupExtensionIntegrationTests.testSuccessful(GrpcCleanupExtensionIntegrationTests.kt:45)
Actually, there were zero interactions with this mock.

Wanted but not invoked:
server.shutdown();
-> at com.asarkar.grpc.test.GrpcCleanupExtensionIntegrationTests.testSuccessful(GrpcCleanupExtensionIntegrationTests.kt:45)
Actually, there were zero interactions with this mock.
```

any advice?

**Comment by asarkar** [comment]
Parameter injection works as expected. I’m unable to provide debugging service for individual users for free.

**Comment by saadlu** [comment]
thanks

if it works and your tests are passing, then it's on me.

thanks for contributing this. 

I sincerely apologies. I did not mean to ask for debugging service.

**Comment by asarkar** [comment]
Thank you for sponsoring me. As a perk for paid sponsorship, you will receive personalized support. I’m reopening this ticket and will look into it shortly.

**Comment by asarkar** [comment]
@saadlu I've determined that this is a bug, and created a PR with a fix that'll be released shortly. Unfortunately, I couldn't find a way to write unit or integration tests to verify the fix, but I've tested it manually with your project, and verified that `Resources.cleanUp` method is invoked when your test is ran.
Thanks for the report.

**Comment by asarkar** [comment]
https://github.com/asarkar/grpc-test/releases/tag/v1.2.2. It might take a few hours to show up in Maven Central.
